### ISSUE TITLE
Better comment emit on tokens

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#17689]
Carrying on from the work initiated in #17557, we should improve our retention of comments where possible. We should check that we retain comments inside:
- [x] `BinaryExpression` (#16584)
- [x] `ReturnStatement` (#17557)
- [x] `YieldExpression` (#22141)
- [x] `AwaitExpression`  (#22141)
- [x] `DeleteExpression`  (#22141)
- [x] `TypeOfExpression`  (#22141)
- [x] `VoidExpression`  (#22141)
- [x] `NewExpression`  (#22141)
- [x] `ElementAccessExpression`  (#22141)
- [x] `PropertyAccessExpression`  (#22141)
- [x] Block-level statements where the comments need to be considered attached to a parenthesis token, such as:  (#22141)
  * [x] `IfStatement`  (#22141)
  * [x] `WhileStatement`  (#22141)
  * [x] `DoStatement` (#22141)
  * [x] `ForStatement` (#22141)
  * [x] `ForInStatement` (#22141)
  * [x] `ForOfStatement` (#22141)
  * [x] `SwitchStatement` (#22141)
  * [x] `WithStatement` (#22141)
  * [x] `ContinueStatement` (#22141)
  * [x] `BreakStatement` (#22141)
  * [x] `CaseStatement` (#22141)
  * [x] `ThrowStatement` (#22141) (future: `ThrowExpression`)
  * [x] `TryStatement` (see #11755)
- [x] `VariableDeclaration` (#22141)
- [ ] `AsExpression` (only visible for ts -> ts transforms)
- [ ] `TypeAssertionExpression` (same as above)
- [ ] `JSXExpression` (in all jsx emit modes) (#41754)
- [x] All import and export kinds (#22141)
- [ ] Literally all multitoken type nodes (that aren't within jsdoc)
  * [ ] `TypePredicateNode`
  * [ ] `TypeQueryNode`
  * [ ] `ConstructorTypeNode`
  * [ ] `FunctionTypeNode`
  * [ ] `ConditionalTypeNode`
  * [ ] `InferTypeNode`
  * [ ] `ThisTypeNode`
  * [ ] `MappedTypeNode`
  * [ ] `IndexedAccessTypeNode`

More? I welcome examples of places where we do not preserve comments on tokens in the middle of nodes, as that is the general vein of comment preservation we're looking at with these.

**Comment by RyanCavanaugh** [comment]
This looks as done as it needs to be; we can take others on a case by case basis
