### ISSUE TITLE
Spec needs various updates for strict null checking

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#20346]
- [ ] [Update predefined types](https://github.com/Microsoft/TypeScript/blob/b8f22f51441495203c96b95969c45a3f78482517/doc/spec.md#381-predefined-types
- [ ] Semantics of `void` - #20006 and #18103.
- [ ] Investigate [whether type queries need to be widened apart from in loose null checks mode](https://github.com/Microsoft/TypeScript/blob/b8f22f51441495203c96b95969c45a3f78482517/doc/spec.md#3810-type-queries) (cases like `let x: typeof undefined`).
