### ISSUE TITLE
Task list: Convert TypeScript repo to project references

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#23324]
* [ ] Remove all `/// <reference` directives; put explicit file lists in tsconfigs
* [ ] Turn on the `no-reference` TSLint rule
* [ ] Move code between files until they're movable to proper subprojects
* [ ] Simplify the jakefile
* [ ] Add sourcemaps for outFile compilations (@weswigham)
* [ ] More?

**Comment by RyanCavanaugh** [comment]
Done
