### ISSUE TITLE
TypeScript 3.1 improved error UX meta-issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#26077]
Continuing on from the release of TypeScript 3.0, we're committed to improving the user experience all around, and following up on both #25310 and #25257.

# Error improvements

* [ ] Seek most-overlapping types in unions (#26450 🏃)
* [x] Better errors on object properties in function/constructor calls (#25695)
* [x] Better hints for uncalled types (#25308)
* [X] Better errors between callable types and unions (#26449)
* [X] Better errors for accidentally called type assertions (#26991)
* [x] Better hints for 'cannot find name' errors (#25309)
* [X] Better error spans with nested arrays and arrow functions (#27030)
* [X] Better errors for accidentally called type assertion (#26991)
* [ ] Better errors on weak type intersections like `IntrinsicAttributes` (#24146 :running_man:)
* [ ] Better errors when matching implementation signatures (#25488)

(:running_man: implies we have an existing PR)

# Related error spans

- [ ] Errors on base members with derived classes (#25033)
- [X] Too few arguments (#25255)
- [ ] Mismatched getters/setters (#25002 🏃)
- [ ] Errors on multiple default exports (#25032 🏃)

(:running_man: implies we have an existing PR)

> Psst, even though the issues are assigned, we'd welcome any help on them!

**Comment by emattias** [comment]
Comparing my DX/UX from when working with flow and TypeScript the error messages is one of the few things that I preferred how flow is doing it. Especially after flow v0.66 release. I would love it if typescript would adopt some for the formatting and helpful information that flow has in their error messages. 

This blog post explains more about the flow 0.66 error message changes: https://medium.com/flow-type/better-flow-error-messages-for-the-javascript-ecosystem-73b6da948ae2

**Comment by emattias** [comment]
There is so much room for improvement here. For example: 
- prettifying/formatting the outputted types
- syntax highlighting
- bold/highligh the conflicting parts

Heres and example of the ginormous unstructured blob of text that is a ts error with big types involved:

```Type '({ expandedRowIds, orderBy, currentPage, filters: { columns: columnFilters, period, categoryIds }, ...restUrlQueryState }: Pick<Overwrite<DataGridUrlQueryStateUrlSerialized, { filters: { columns: { promotionName?: string | undefined; startDate?: string | undefined; endDate?: string | undefined; "sumFacts.switching.amount"?: string | undefined; "sumFacts.netLift.profit"?: string | undefined; "sumFacts.netLift.amount"?: string | undefined; }; period: Date[]; categoryIds: string[]; }; }>, "hiddenColumnNames" | "filters" | "orderBy" | "expandedRowIds" | "currentPage">, pageSize: any) => Dictionary<any>' is not assignable to type '(a: Overwrite<DataGridUrlQueryStateUrlSerialized, { filters: { columns: { promotionName?: string | undefined; startDate?: string | undefined; endDate?: string | undefined; "sumFacts.switching.amount"?: string | undefined; "sumFacts.netLift.profit"?: string | undefined; "sumFacts.netLift.amount"?: string | undefined; }; period: Date[]; categoryIds: string[]; }; }>) => DataGridQueryVariables'.```

Another interesting thing that happened with flow is the  [glow](https://github.com/jamiebuilds/glow) that formatted errors and made them way more readable. I believe all or some of glows functionality got integrated into flow itsself.

**Comment by DanielRosenwasser** [comment]
Yup, agreed. We have some work that will enable that, but this is a pretty old issue at this point. Opening a specific issue to track that would be super helpful.

**Comment by emattias** [comment]
Tracking exactly what? Should I just create an issue of my last comment or should I break it down in some way?

**Comment by DanielRosenwasser** [comment]
Yup, something like that but with context that you're talking about the command line

**Comment by emattias** [comment]
Done: https://github.com/Microsoft/TypeScript/issues/29059
