### ISSUE TITLE
Release Automation Meta Issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37196]
We're trying to find ways to reduce the amount of manual work that a release requires. This currently includes

* [x] https://github.com/microsoft/TypeScript/issues/36863
* [ ] https://github.com/microsoft/TypeScript/issues/36864
* [ ] https://github.com/microsoft/TypeScript/issues/34818

More may be added to this list over time

**Comment by orta** [comment]
It doesn't look like we deploy the main npm packages through automation, but I think I can make it so publishing [a new release](https://github.com/microsoft/TypeScript/releases) could trigger a build for the playground (via the same mechanism we do PR deploys)
