### ISSUE TITLE
Partial Semantic Mode Meta-Issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#39035]
https://github.com/microsoft/TypeScript/pull/38561 implements the core idea proposed in https://github.com/microsoft/TypeScript/issues/37713.

Beyond that, there is still a set of UX issues that we should probably address:

- [ ] make find-all-refs work on unresolved locals (https://github.com/microsoft/TypeScript/issues/38836)
- [ ] better display experience on the syntax server (https://github.com/microsoft/TypeScript/issues/39032)
- [ ] expand when `isNewIdentifierLocation` on the syntax server (https://github.com/microsoft/TypeScript/issues/39033)
- [ ] consider loose completions on the syntax server on unresolved/error types (https://github.com/microsoft/TypeScript/issues/39034)

**Comment by DanielRosenwasser** [comment]
@sheetalkamat @amcasey @mjbvz @RyanCavanaugh @minestarks

**Comment by Jack-Works** [comment]
it should also support file navigation on a relative filename (`import './file/x[cursor here]/y'`)
