### ISSUE TITLE
Running TS Server in a web worker

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#39707]
Tracks the high-level work required to run the TypeScript server in a web worker. #39656 has an initial draft of this work.

**TODO V1**
- [ ] Enable reading standard library `d.ts` files
- [ ] Address todo comments in #39656
- [ ] Ship web enabled server in TS nightly builds 

**TODO: Post V1**
- [ ] Enable  type acquisition 

/cc @RyanCavanaugh @DanielRosenwasser

**Comment by Rheeseyb** [comment]
Looks like all of V1 here has been completed - is the second part actively in progress at all? Are you looking for any help with this? In our own project we have something already implemented that is running a TS compiler in a worker thread using an in memory filesystem, which it seems would be relevant here though would need a fair amount of work to port it across to the TS server. We're likely going to have to do a version of that work anyway, so if possible we'd like to contribute that to this.

**Comment by mjbvz** [comment]
Closing this as we now have tsserver running in web

Will open new issue for  type acquisition
