### ISSUE TITLE
Language service support for classic JavaScript patterns meta-issue

### ISSUE THREAD

**Issue by minestarks** [microsoft/TypeScript#40025]
One consistent piece of feedback from users who have been using Visual Studio long-term to develop JavaScript-only projects is that the old, execution-based language service in Visual Studio 2015 did a better job picking up certain common JavaScript patterns than the TypeScript language service.

This is a meta-issue to collect specific instances where TypeScript didn't do as good a job as VS 2015 IntelliSense. By targeting these specific fixes we hope to improve the experience of users upgrading from VS 2015, as well as improve our type inference for pure JavaScript in general.

* [x] Function declaration with aliased `this` not treated as a constructor #39842 
* [x] Prototype assignment doesn't work on default-assigned constructor functions #39167
* [ ] Prototype assignment should take the type of the initializer and not require a literal #39166
* [ ] Assignments to global objects in Javascript should be global declarations #22446
* [ ] `@description` JSDoc tag interferes with callback parameter documentation #37346
