### ISSUE TITLE
[Meta] Refactors of React hooks

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#41795]
## Search Terms
refactor, react, hooks

## Suggestion

Provide a series of refactors about react hooks.

## Use Cases

In my recently works. I have alway Wrap function, value declarations, expressions into `React.useMemo` or `React.useCallback`.
And I must find all the depends on the selection. And always missing some deps. It's not a good experience.

Could we provide some refactors to wrap something into well-known react hooks? 

I'm not sure where's the **bar** of patterns we are allowed. but we have already had something like 'react-jsx'.

## Examples

```tsx

const Comp = props => {
  const value = props.a + props.b;

  const handleClick = () => {
    console.log('foo', value)
  }

  return <div onClick={handleClick}><SomeHeavyComponent value={value}/></div>
}

```

- When I select `props.a + props.b`, convert into 

```tsx
React.useMemo(() => props.a + props.b, [props.a, props.b]);
```

- When I select `handleClick ` or the lambda, convert into
```tsx
const handleClick = React.userCallback() => {
  console.log('foo', value)
}, [value])
```
- When I select `<SomeHeavyComponent value={value}/>`, convert into 
```tsx
React.useMemo(() => (<SomeHeavyComponent value={value}/>), [value])
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by stkevintan** [comment]
awesome, looks good to me
