### ISSUE TITLE
Add build-in TODO() function that throws Unimplemented error

### ISSUE THREAD

**Issue by dranovsk** [microsoft/TypeScript#43001]
# Suggestion

## 🔍 Search Terms

Unimplemented
TODO

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add build-in Kotlin like TODO() function and UnimplementedError class:

```typescript
export class UnimplementedError extends Error {
  constructor(public reason = 'Not Implemented') {
    super('Not Implemented');
  }
}

export function TODO(reason?: string): void {
  throw new UnimplementedError(reason);
} 
```

## 📃 Motivating Example

Cli generated empty methods/constructors produce multiple, not so useful, linting errors, that can be disabled:

```typescript
export class AboutComponent implements OnInit {
  constructor() {    
  }

  ngOnInit(): void {
  }
}
```

eslint output:
Unexpected empty constructor.
Lifecycle method ngOnInit should not be empty
Unexpected empty method 'ngOnInit'.

Adding TODO() function that throws Unimplemented exception with optional reason, will be caught by compiler, testing tools, runtime errors, picked up by IDE TODO parsers, etc.

```typescript
export class AboutComponent implements OnInit {
  constructor() {
    TODO();  
  }

  ngOnInit(): void {
    TODO('Implement component initialization.');
  }
}
```

Jest test:
Error: Not Implemented

## 💻 Use Cases

As described above.

**Comment by MartinJohns** [comment]
> [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

You might want to check this point again.
