### ISSUE TITLE
Treat `new URL('relativePathHere', import.meta.url)` as assets.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#45955]
# Suggestion

When using a file in TypeScript, `new URL("./file.png", import.meta.url)`, TypeScript should copy this file to the output folder, like what it did for importing `JSON` files.

## 🔍 Search Terms

new URL import meta url

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

This is useful when writing a library with assets referenced otherwise we need extra steps to copy those files.

**Comment by nmain** [comment]
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

> Non-goals
> Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

**Comment by Jack-Works** [comment]
> https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
> 
> > Non-goals
> > Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

But why it can copy JSON files with resolveJsonModule? And I belive they'll also do this for wasm files (https://github.com/microsoft/TypeScript/pull/39784)

**Comment by andrewbranch** [comment]
How are we supposed to know that `URL` is special? It’s just a constructor defined in a lib file.

**Comment by Jack-Works** [comment]
> How are we supposed to know that `URL` is special? It’s just a constructor defined in a lib file.

It's hard coded in all of the toolchains like how they treat `require`.

**Comment by andrewbranch** [comment]
Therein lies the answer to

> But why it can copy JSON files with resolveJsonModule?

**Comment by Jack-Works** [comment]
> Therein lies the answer to
> 
> > But why it can copy JSON files with resolveJsonModule?

Because in `resolveJsonModule`, TypeScript actually parse and generate type information for JSON module right

**Comment by andrewbranch** [comment]
Yes, and more generally, we have to process imports and exports in order for modules to work, and there is unambiguous syntax, not dependent on type definitions, that triggers an import.
