### ISSUE TITLE
Meta: Normative Changes for Explicit Resource Management

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#58622]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The following are recent normative changes to the Explicit Resource Management proposal that need to be implemented by TypeScript:

- [x] tc39/proposal-explicit-resource-management#180
  - Related: #58077
  - Addressed by: #58624
- [x] tc39/proposal-explicit-resource-management#218
  - Addressed by: #58624
- [x] tc39/proposal-explicit-resource-management#217
  - Addressed by: #58624
- [x] ~~tc39/proposal-explicit-resource-management#194~~
  - Not affected (implementation already empties stack)
- [x] ~~tc39/proposal-explicit-resource-management#220~~
  - Not affected
- [x] ~~tc39/proposal-explicit-resource-management#222~~
  - Already supported
