### ISSUE TITLE
site:github.com/microsoft/resume-engrave-ct-03

### ISSUE THREAD

**Issue by abirhasan132** [microsoft/TypeScript#58689]
### 🔎 Search Terms

curl -X 'GET' \
  'https://codeberg.org/api/v1/activitypub/user-id/11103' \
  -H 'accept: application/json'
Request URL
https://codeberg.org/api/v1/activitypub/user-id/11103 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://codeberg.org/api/v1/activitypub/user-id/11103/inbox

### 💻 Code

```ts
// Your code here
```
curl -X 'POST' \
  'https://codeberg.org/api/v1/activitypub/user-id/11103/inbox' \
  -H 'accept: application/json' \
  -d ''

### 🙁 Actual behavior

const CounterSymbol = Symbol('CounterSymbol');
type Counter = 0 | number & { [CounterSymbol]: true };

// This manual assertion is correct. Sense of this type is impossibility of misc changes.
const intInc = (counter: Counter): Counter => (counter + 1) as Counter;

let counter: Counter = 0;

counter = 3;
counter = counter - 100; // must be error but no, thus it's the leak in typization
counter -= 100; // must be error but no, thus it's the leak in typization

class A {
  protected counter: Counter = 0;

  public inc(): void {
    this.counter = counter - 100;
    this.counter -= 100; // must be error but no, thus it's the leak in typization
  }
}

### 🙂 Expected behavior

(https://github.com/microsoft/TypeScript/assets/170718148/e88590bb-7fb8-4ce4-92ae-0391debf17c6)

### Additional information about the issue

(https://github.com/microsoft/TypeScript/assets/170718148/55423698-ba78-45ec-a005-4eb3514abdfb)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/TypeScript/issues/54102
- [ ] https://github.com/microsoft/TypeScript/pull/55371
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/TypeScript/issues/54102
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/TypeScript/issues/58685
- [ ] https://github.com/microsoft/TypeScript/pull/55371
- [ ] https://github.com/microsoft/TypeScript/issues/58473
- [ ] https://github.com/microsoft/TypeScript/pull/58489
- [ ] https://github.com/microsoft/TypeScript/issues/54102
- [ ] https://github.com/microsoft/TypeScript/issues/58687
- [ ] https://github.com/microsoft/TypeScript/issues/58688
- [ ] https://github.com/microsoft/TypeScript/issues/58686
- [ ] https://github.com/microsoft/TypeScript/pull/58654
- [ ] https://github.com/microsoft/TypeScript/issues/58682
- [ ] https://github.com/microsoft/TypeScript/pull/56681
- [ ] https://github.com/microsoft/TypeScript/pull/58188
- [ ] https://github.com/microsoft/TypeScript/issues/25945
- [ ] https://github.com/microsoft/TypeScript/pull/58320
- [ ] https://github.com/microsoft/TypeScript/issues/50715
- [ ] https://github.com/microsoft/TypeScript/pull/58084
- [ ] https://github.com/microsoft/TypeScript/pull/58608
- [ ] https://github.com/microsoft/TypeScript/issues/58684
- [ ] https://github.com/microsoft/TypeScript/pull/58480
- [ ] https://github.com/microsoft/TypeScript/pull/58526
- [ ] https://github.com/microsoft/TypeScript/pull/45347
- [ ] https://github.com/microsoft/TypeScript/pull/58679
- [ ] https://github.com/microsoft/TypeScript/pull/54513
```

**Comment by abirhasan132** [comment]
#58689

**Comment by abirhasan132** [comment]
// Your code here

**Comment by abirhasan132** [comment]
https://github.com/microsoft/TypeScript/issues/58689#issue-2322427589

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
